#Every field must have some string value. So when the base is XLM, do not leave base_issuer blank
#To aggregate volume across issuers: enter a comma seperated list of asset codes in "counter" and a list of issuers in "counter_issuer"
#The first counter value corresponds to the first counter_issuer value and so on.
#EXAMPLE
#[[pair]]
#name = "XLM_BTC"
#base = "XLM"
#base_issuer = "native"
#counter = ["BTC", "EURT"]
#counter_issuer = ["GATEMHCCKCY67ZUCKTROYN24ZYT5GK4EQZ65JJLDHKHRUZI3EUEKMTCH", "GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"]

Title = "Currency Pairs"

[[pair]]
name = "XLM_BTC"
base = "XLM"
base_issuer = "native"
counter = ["BTC","BTC", "BTC"]
counter_issuer = ["GATEMHCCKCY67ZUCKTROYN24ZYT5GK4EQZ65JJLDHKHRUZI3EUEKMTCH", #naobtc.com
     "GDXTJEK4JZNSTNQAWA53RZNS2GIKTDRPEUWDXELFMKU52XNECNVDVXDI", 
     "GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF"]

[[pair]]
name = "XLM_CNY"
base = "XLM"
base_issuer = "native" 
counter = ["CNY"]
counter_issuer = ["GAREELUB43IRHWEASCFBLKHURCGMHE5IF6XSE7EXDLACYHGRHM43RFOX"]

[[pair]]
name = "XLM_EUR"
base = "XLM"
base_issuer = "native"
counter = ["EURT"]
counter_issuer = ["GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"]

[[pair]]
name = "XLM_JPY"
base = "XLM"
base_issuer = "native"
counter = ["JPY"]
counter_issuer = ["GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM"]

[[pair]]
name = "XLM_PHP"
base = "XLM"
base_issuer = "native"
counter = ["PHP"]
counter_issuer = ["GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"]

[[pair]]
name = "XLM_XRP"
base = "XLM"
base_issuer = "native"
counter = ["XRP"]
counter_issuer = ["GA7FCCMTTSUIC37PODEL6EOOSPDRILP6OQI5FWCWDDVDBLJV72W6RINZ"]

#[[pair]]
#name = "XLM_GFT"
#base = "XLM"
#base_issuer = "native"
#counter = ["GFT"]
#counter_issuer = ["GAAZUE4PKMKLA7QC2MPUIUXY7BZK2WUCK7Q5EELSDLK4FE3X4DZTSCKN"]


#[[pair]]
#name = "XLM_MOBI"
#base = "XLM"
#base_issuer = "native"
#counter = ["MOBI"]
#counter_issuer = ["GDCIUCGL7VEMMF6VYJOW75KQ5ZCLHAQBRM6EPFTKCRWUYVUOOYQCKC5A"]

#[[pair]]
#name = "XLM_SEED"
#base = "XLM"
#base_issuer = "native"
#counter = ["SEED"]
#counter_issuer = ["GDPFSEBZO2W4TLWZO7FIMMG3QONHXYVF6LUULI6HUJS6PJLE4TRZEXLF"]

[[pair]]
name = "XLM_XEL"
base = "XLM"
base_issuer = "native"
counter = ["XEL"]
counter_issuer = ["GAXELY4AOIRVONF7V25BUPDNKZYIVT6CWURG7R2I6NQU26IQSQODBVCS"]

#[[pair]]
#name = "BTC_XEL"
#base = "BTC"
#base_issuer = "GATEMHCCKCY67ZUCKTROYN24ZYT5GK4EQZ65JJLDHKHRUZI3EUEKMTCH"
#counter = ["XEL"]
#counter_issuer = ["GAXELY4AOIRVONF7V25BUPDNKZYIVT6CWURG7R2I6NQU26IQSQODBVCS"]

#[[pair]]
#name = "XLM_LTC"
#base = "XLM"
#base_issuer = "native"
#counter = ["LTC"]
#counter_issuer = ["GC5LOR3BK6KIOK7GKAUD5EGHQCMFOGHJTC7I3ELB66PTDFXORC2VM5LP"]

#[[pair]]
#name = "XLM_EQD"
#base = "XLM"
#base_issuer = "native"
#counter = ["EQD"]
#counter_issuer = ["GCGEQJR3E5BVMQYSNCHPO6NPP3KOT4VVZHIOLSRSNLE2GFY7EWVSLLTN"]

#[[pair]]
#name = "XLM_ICN"
#base = "XLM"
#base_issuer = "native"
#counter = ["ICN"]
#counter_issuer = ["GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR"] # apay.io


